export interface InformationModel {
    applicant_i_information_id?: number,
    firstname?: string,
    middlename?: string,
    lastname?: string,
    email?: string,
    civilStatus?: string,
    contactnumber?: string,
    birthdate?: string,
    religion?: string,
    province?: string,
    cities?: string,
    barangay?: string,
    zipcode?: number,
    expectedSalary?: number,
    positionSelected?: string;
    applicantName?:string,
    blood_type?:string,
    gender?:string,
    nickname?:string,
    desiredPosition?:string,
}
